-intstyle "ise" -incremental -lib "secureip" -o "D:/Sem4/CompArch/Lab/Assgt4-CompArch/Test_Control_isim_beh.exe" -prj "D:/Sem4/CompArch/Lab/Assgt4-CompArch/Test_Control_beh.prj" "work.Test_Control" 
